repositories:
- name: stable
  url: https://charts.helm.sh/stable

environments:
  dev:
    values:
    - ${PWD}/environments/dev/values.yaml
  qt:
    values:
    - ${PWD}/environments/qt/values.yaml
    - ${PWD}/environments/promote.yaml
  testing:
    values:
    - ${PWD}/environments/testing/values.yaml
    - ${PWD}/environments/promote.yaml

releases:
- name: my-app
  namespace: {{ .Environment.Name }}
  chart: ${PWD}/charts/my-app
  values:
  - "${PWD}/environments/{{ .Environment.Name }}/values.yaml"
  wait: true
  timeout: 300
