repositories:
- name: stable
  url: https://charts.helm.sh/stable

environments:
  dev:
    values:
    - /environments/dev/values.yaml
  qt:
    values:
    - /environments/qt/values.yaml
    - /environments/promote.yaml
  testing:
    values:
    - /environments/testing/values.yaml
    - /environments/promote.yaml

releases:
- name: my-app
  namespace: {{ .Environment.Name }}
  chart: /charts/my-app
  values:
  - "/environments/{{ .Environment.Name }}/values.yaml"
  wait: true
  timeout: 300
