apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: my-repo-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: kirmadaa/GitOps
      labels:
        - self-hosted
        - linux
        - x64
