name: Dev Deployment
on:
  push:
    branches: [main]
    paths:
      - 'environments/dev/**'
      - 'charts/**'

jobs:
  deploy:
    runs-on: self-hosted
    environment: dev
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.1

    - name: Validate file structure
      run: | 
        ls -la
        ls -la environments/dev/
        ls -la charts/my-app/
        
    - name: Install Helmfile
      run: |
        curl -fsSL -o helmfile_linux_amd64 https://github.com/roboll/helmfile/releases/download/v0.144.0/helmfile_linux_amd64
        chmod +x helmfile_linux_amd64
        sudo mv helmfile_linux_amd64 /usr/local/bin/helmfile
        
    - name: Deploy to Dev
      run: |
        helmfile -e dev apply --skip-diff-on-install --suppress-secrets
