name: Promote
on:
  repository_dispatch:
    types: [promote]
jobs:
  bump-dev:
    runs-on: self-hosted
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - run: echo "IMAGE_TAG=${{ github.event.client_payload.tag }}" >> $GITHUB_ENV
      - run: yq -i '.image.tag = strenv(IMAGE_TAG)' values/dev.yaml
      - run: git commit -am "dev → $IMAGE_TAG" && git push
  bump-qt:
    needs: bump-dev
    runs-on: self-hosted
    environment: qt
    steps: … (same for `values/qt.yaml`)
  bump-testing:
    needs: bump-qt
    runs-on: self-hosted
    environment: testing
    steps: … (same for `values/testing.yaml`)
