name: Promote Artifacts
on:
  workflow_run:
    workflows: ["Dev Deployment"]
    types:
      - completed

jobs:
  promote:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      
    - name: Get Dev Image Tag
      id: get-tag
      run: |
        TAG=$(helmfile -e dev template | grep "image:" | awk -F':' '{print $3}' | tr -d ' ' | tr -d '"')
        echo "tag=${TAG}" >> $GITHUB_OUTPUT
      
    - name: Create Promotion File
      run: |
        echo "image:" > environments/promote.yaml
        echo "  tag: ${{ steps.get-tag.outputs.tag }}" >> environments/promote.yaml
        echo "promotedFrom: dev" >> environments/promote.yaml
        echo "promotionTime: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> environments/promote.yaml
        
    - name: Create PR for QT
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: promote/qt-${{ steps.get-tag.outputs.tag }}
        base: main
        title: "[PROMOTE] Dev to QT: ${{ steps.get-tag.outputs.tag }}"
        body: |
          Automatically promoted from Dev environment
          Image Tag: ${{ steps.get-tag.outputs.tag }}
        labels: promotion,qt